"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-29 15:32:16.201990
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_admin_id'), 'audit_logs', ['admin_id'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource', 'resource_id'], unique=False)
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('smtp', 'api', name='provider_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('tls_mode', sa.Enum('starttls', 'ssl', 'none', name='tls_mode', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('from_email', sa.String(length=320), nullable=False),
    sa.Column('from_name', sa.String(length=128), nullable=True),
    sa.Column('hourly_limit', sa.Integer(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('per_second_limit', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'WARNING', 'DEGRADED', 'DISABLED', name='provider_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('health_score', sa.Float(), server_default=sa.text('100'), nullable=False),
    sa.Column('consecutive_bad_windows', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('webhook_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_test_message', sa.String(length=512), nullable=True),
    sa.Column('status_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers')),
    sa.UniqueConstraint('provider_name', name=op.f('uq_providers_provider_name'))
    )
    op.create_index(op.f('ix_providers_status'), 'providers', ['status'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('workers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_jobs', sa.Integer(), server_default=sa.text('4'), nullable=False),
    sa.Column('status', sa.Enum('online', 'warning', 'offline', name='worker_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('disabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('credential_hash', sa.String(length=64), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cpu', sa.Float(), nullable=True),
    sa.Column('memory', sa.Float(), nullable=True),
    sa.Column('active_jobs', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('current_rate', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workers')),
    sa.UniqueConstraint('worker_id', name=op.f('uq_workers_worker_id'))
    )
    op.create_table('provider_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=False),
    sa.Column('key_version', sa.String(length=16), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_credentials_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_credentials')),
    sa.UniqueConstraint('provider_id', name=op.f('uq_provider_credentials_provider_id'))
    )
    op.create_table('provider_health_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('successes', sa.Integer(), nullable=False),
    sa.Column('auth_failures', sa.Integer(), nullable=False),
    sa.Column('connection_failures', sa.Integer(), nullable=False),
    sa.Column('timeouts', sa.Integer(), nullable=False),
    sa.Column('deferrals', sa.Integer(), nullable=False),
    sa.Column('bounces', sa.Integer(), nullable=False),
    sa.Column('complaints', sa.Integer(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_health_logs_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_health_logs'))
    )
    op.create_index('ix_provider_health_logs_provider_time', 'provider_health_logs', ['provider_id', 'created_at'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'disabled', name='user_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('totp_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_index('uq_users_username_lower', 'users', [sa.literal_column('lower(username)')], unique=True)
    op.create_table('worker_heartbeats',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cpu', sa.Float(), nullable=True),
    sa.Column('memory', sa.Float(), nullable=True),
    sa.Column('active_jobs', sa.Integer(), nullable=False),
    sa.Column('current_rate', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_worker_heartbeats_worker_id_workers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_heartbeats'))
    )
    op.create_index('ix_worker_heartbeats_worker_time', 'worker_heartbeats', ['worker_id', 'timestamp'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('from_name', sa.String(length=128), nullable=True),
    sa.Column('from_email', sa.String(length=320), nullable=True),
    sa.Column('reply_to', sa.String(length=320), nullable=True),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('text_body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'QUEUED', 'PROCESSING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='campaign_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('total_recipients', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('invalid_recipients', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('duplicate_recipients', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('processed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('sent', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('delivered', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('bounced', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('complained', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('deferred', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('unsubscribed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('skipped_suppressed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('batches_built', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('consent_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_confirmed_by', sa.UUID(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consent_confirmed_by'], ['users.id'], name=op.f('fk_campaigns_consent_confirmed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_campaigns_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_campaigns_provider_id_providers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_campaigns_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index('idx_campaign_user', 'campaigns', ['user_id'], unique=False)
    op.create_index('ix_campaigns_status', 'campaigns', ['status'], unique=False)
    op.create_table('provider_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'revoked', name='assignment_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_provider_assignments_assigned_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_assignments_provider_id_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_provider_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_assignments'))
    )
    op.create_index(op.f('ix_provider_assignments_provider_id'), 'provider_assignments', ['provider_id'], unique=False)
    op.create_index(op.f('ix_provider_assignments_user_id'), 'provider_assignments', ['user_id'], unique=False)
    op.create_index('uq_provider_assignments_active', 'provider_assignments', ['user_id', 'provider_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('app', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.UUID(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('suppression_list',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('scope_user_id', sa.UUID(), nullable=True),
    sa.Column('email_normalized', sa.String(length=320), nullable=False),
    sa.Column('type', sa.Enum('unsubscribe', 'hard_bounce', 'complaint', 'invalid', 'admin_blocked', name='suppression_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('source_event_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_suppression_list_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scope_user_id'], ['users.id'], name=op.f('fk_suppression_list_scope_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppression_list'))
    )
    op.create_index('idx_suppression_lookup', 'suppression_list', ['email_normalized'], unique=False)
    op.create_index('uq_suppression_scope_email', 'suppression_list', ['scope_user_id', 'email_normalized'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_system_settings_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_settings'))
    )
    op.create_table('user_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('hourly_limit', sa.Integer(), nullable=True),
    sa.Column('per_second_limit', sa.Integer(), nullable=True),
    sa.Column('max_batch_size', sa.Integer(), nullable=True),
    sa.Column('max_recipients_per_campaign', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_user_limits_updated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_limits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_limits')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_limits_user_id'))
    )
    op.create_table('campaign_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('retry_round', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'claimed', 'processing', 'completed', 'failed', 'retry', 'dead_letter', 'cancelled', name='batch_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_batches_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_batches')),
    sa.UniqueConstraint('campaign_id', 'sequence_no', name='uq_campaign_batches_seq')
    )
    op.create_table('campaign_recipients',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_normalized', sa.String(length=320), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('pending', 'queued', 'sent', 'delivered', 'deferred', 'bounced', 'failed', 'complained', 'unsubscribed', 'suppressed', 'cancelled', name='recipient_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['campaign_batches.id'], name=op.f('fk_campaign_recipients_batch_id_campaign_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_recipients_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_recipients')),
    sa.UniqueConstraint('campaign_id', 'email_normalized', name='uq_campaign_recipients_campaign_email')
    )
    op.create_index('ix_campaign_recipients_batch_status', 'campaign_recipients', ['batch_id', 'status'], unique=False)
    op.create_index('ix_campaign_recipients_campaign_status', 'campaign_recipients', ['campaign_id', 'status'], unique=False)
    op.create_index('ix_campaign_recipients_provider_message_id', 'campaign_recipients', ['provider_message_id'], unique=False, postgresql_where=sa.text('provider_message_id IS NOT NULL'))
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'claimed', 'processing', 'completed', 'failed', 'retry', 'dead_letter', 'cancelled', name='job_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_attempt_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['campaign_batches.id'], name=op.f('fk_jobs_batch_id_campaign_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_jobs_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_jobs_provider_id_providers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_jobs_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_jobs_worker_id_workers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('batch_id', name=op.f('uq_jobs_batch_id')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_jobs_idempotency_key'))
    )
    op.create_index('idx_jobs_available_at', 'jobs', ['available_at'], unique=False)
    op.create_index('idx_jobs_claimable', 'jobs', ['status', 'available_at'], unique=False, postgresql_where=sa.text("status IN ('pending', 'retry')"))
    op.create_index('idx_jobs_lease', 'jobs', ['lease_expires_at'], unique=False, postgresql_where=sa.text("status IN ('claimed', 'processing')"))
    op.create_index('idx_jobs_status', 'jobs', ['status'], unique=False)
    op.create_index('ix_jobs_campaign_status', 'jobs', ['campaign_id', 'status'], unique=False)
    op.create_table('email_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('recipient_id', sa.BigInteger(), nullable=True),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('queued', 'processing', 'sent', 'delivered', 'deferred', 'bounced', 'failed', 'complained', 'unsubscribed', 'suppressed', name='event_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_email_events_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_email_events_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_email_events_provider_id_providers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_events'))
    )
    op.create_index('idx_events_campaign_time', 'email_events', ['campaign_id', 'created_at'], unique=False)
    op.create_index('ix_email_events_created_at', 'email_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_events_user_id'), 'email_events', ['user_id'], unique=False)
    op.create_index('uq_email_events_provider_dedupe', 'email_events', ['provider_id', 'provider_message_id', 'event_type'], unique=True, postgresql_where=sa.text("provider_message_id IS NOT NULL AND event_type IN ('delivered', 'bounced', 'complained', 'unsubscribed')"))
    op.create_table('job_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.Enum('running', 'completed', 'failed', 'lease_expired', 'released', name='attempt_outcome', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_attempts_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_job_attempts_worker_id_workers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_attempts'))
    )
    op.create_index(op.f('ix_job_attempts_job_id'), 'job_attempts', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_attempts_job_id'), table_name='job_attempts')
    op.drop_table('job_attempts')
    op.drop_index('uq_email_events_provider_dedupe', table_name='email_events', postgresql_where=sa.text("provider_message_id IS NOT NULL AND event_type IN ('delivered', 'bounced', 'complained', 'unsubscribed')"))
    op.drop_index(op.f('ix_email_events_user_id'), table_name='email_events')
    op.drop_index('ix_email_events_created_at', table_name='email_events')
    op.drop_index('idx_events_campaign_time', table_name='email_events')
    op.drop_table('email_events')
    op.drop_index('ix_jobs_campaign_status', table_name='jobs')
    op.drop_index('idx_jobs_status', table_name='jobs')
    op.drop_index('idx_jobs_lease', table_name='jobs', postgresql_where=sa.text("status IN ('claimed', 'processing')"))
    op.drop_index('idx_jobs_claimable', table_name='jobs', postgresql_where=sa.text("status IN ('pending', 'retry')"))
    op.drop_index('idx_jobs_available_at', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_campaign_recipients_provider_message_id', table_name='campaign_recipients', postgresql_where=sa.text('provider_message_id IS NOT NULL'))
    op.drop_index('ix_campaign_recipients_campaign_status', table_name='campaign_recipients')
    op.drop_index('ix_campaign_recipients_batch_status', table_name='campaign_recipients')
    op.drop_table('campaign_recipients')
    op.drop_table('campaign_batches')
    op.drop_table('user_limits')
    op.drop_table('system_settings')
    op.drop_index('uq_suppression_scope_email', table_name='suppression_list', postgresql_nulls_not_distinct=True)
    op.drop_index('idx_suppression_lookup', table_name='suppression_list')
    op.drop_table('suppression_list')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('uq_provider_assignments_active', table_name='provider_assignments', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_provider_assignments_user_id'), table_name='provider_assignments')
    op.drop_index(op.f('ix_provider_assignments_provider_id'), table_name='provider_assignments')
    op.drop_table('provider_assignments')
    op.drop_index('ix_campaigns_status', table_name='campaigns')
    op.drop_index('idx_campaign_user', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_worker_heartbeats_worker_time', table_name='worker_heartbeats')
    op.drop_table('worker_heartbeats')
    op.drop_index('uq_users_username_lower', table_name='users')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index('ix_provider_health_logs_provider_time', table_name='provider_health_logs')
    op.drop_table('provider_health_logs')
    op.drop_table('provider_credentials')
    op.drop_table('workers')
    op.drop_table('roles')
    op.drop_index(op.f('ix_providers_status'), table_name='providers')
    op.drop_table('providers')
    op.drop_table('permissions')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_admin_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
