"""provider bounce mailbox + explicit delivery-reporting flag (design DS-16)

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-29 19:25:49.540055
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('bounce_mailbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('providers', sa.Column('bounce_mailbox_secret_encrypted', sa.Text(), nullable=True))
    op.add_column('providers', sa.Column('bounce_last_polled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('providers', sa.Column('bounce_last_error', sa.String(length=512), nullable=True))
    op.add_column('providers', sa.Column('bounce_processed_total', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('providers', sa.Column('reports_delivery', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###
    # Before 0003 a webhook secret implied "the provider confirms deliveries"; keep that behaviour.
    op.execute("UPDATE providers SET reports_delivery = true WHERE webhook_secret_encrypted IS NOT NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'reports_delivery')
    op.drop_column('providers', 'bounce_processed_total')
    op.drop_column('providers', 'bounce_last_error')
    op.drop_column('providers', 'bounce_last_polled_at')
    op.drop_column('providers', 'bounce_mailbox_secret_encrypted')
    op.drop_column('providers', 'bounce_mailbox')
    # ### end Alembic commands ###
