"""recipient imports from object storage (design DS-21)

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-29 20:18:31.219834
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipient_imports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('replace', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('bytes_read', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('rows', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('imported', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('invalid', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('duplicates', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('invalid_samples', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_recipient_imports_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recipient_imports_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipient_imports'))
    )
    op.create_index(op.f('ix_recipient_imports_campaign_id'), 'recipient_imports', ['campaign_id'], unique=False)
    op.create_index('ix_recipient_imports_queue', 'recipient_imports', ['created_at'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipient_imports_queue', table_name='recipient_imports', postgresql_where=sa.text("status = 'queued'"))
    op.drop_index(op.f('ix_recipient_imports_campaign_id'), table_name='recipient_imports')
    op.drop_table('recipient_imports')
    # ### end Alembic commands ###
