"""campaign template tags: #MASSAGE# texts and per-campaign tag seed (design DS-24)

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-29 20:34:58.416994
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('message_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('campaigns', sa.Column('tag_seed', sa.String(length=64), nullable=True))
    # Existing campaigns get a random 64-hex seed (gen_random_uuid() is built in since PostgreSQL 13).
    op.execute("UPDATE campaigns SET tag_seed = replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', '')")
    op.alter_column('campaigns', 'tag_seed', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'tag_seed')
    op.drop_column('campaigns', 'message_list')
    # ### end Alembic commands ###
