"""worker pools for autoscaled instances (design DS-23)

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-29 20:50:52.813780
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0009'
down_revision: str | None = '0008'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('is_pool', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('workers', sa.Column('pool_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_workers_pool_id'), 'workers', ['pool_id'], unique=False)
    op.create_foreign_key(op.f('fk_workers_pool_id_workers'), 'workers', 'workers', ['pool_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_workers_pool_id_workers'), 'workers', type_='foreignkey')
    op.drop_index(op.f('ix_workers_pool_id'), table_name='workers')
    op.drop_column('workers', 'pool_id')
    op.drop_column('workers', 'is_pool')
    # ### end Alembic commands ###
